name: reviewdog

on:
  pull_request:
    branches:
      - development

jobs:
  eslint:
    name: check_eslint_error
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: eslint review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          eslint_flags: './**/*.{vue,ts,js}'
  stylelint:
    name: check_stylelint_error
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: stylelint review
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          stylelint_input: '**/*.{css,scss,vue}'
  
  unittest:
    name: test_generate_test_script
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: exec unittest
        run: |
          cd $GITHUB_WORKSPACE
          python tool/convert/test_convert_csv_to_json.py
